### ISSUE TITLE
`require': cannot load such file -- bundler (LoadError)

### ISSUE THREAD

**Issue by eboatwright** [loureirorg/rb2exe#14]
I installed ruby 2.2.2, and the rb2exe gem. I've been trying to get this to work for a day and a half now. This is the entire error:
/Users/[USER]/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
        from /Users/[USER]/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/[USER]/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rb2exe-0.3.1/bin/rb2exe:9:in `<top (required)>'
        from /Users/[USER]/.rbenv/versions/2.2.2/bin/rb2exe:23:in `load'
        from /Users/[USER]/.rbenv/versions/2.2.2/bin/rb2exe:23:in `<main>'

**Comment by theendcomplete** [comment]
Have you tried `gem install bundler`?)

**Comment by eboatwright** [comment]
it says:
"ERROR: Error installing bundler:
bundler requires Ruby version >= 2.3.0."
So that won't work, because rb2exe requires Ruby version == 2.2.2. :(

**Comment by Sprachprofi** [comment]
Worked for me with `gem install bundler -v '1.9'`

**Comment by eboatwright** [comment]
This may have fixed it, but as I have stopped using Ruby for my projects, I'll close this issue at that.
Thank you for your reply!
