### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by AwesomeWithRex** [loureirorg/rb2exe#15]
Whenever I do "gem install rb2exe" in my command prompt it says "ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (bin/traveling-ruby-2.2.2/osx/lib/libcrypto.1.0.0.dylib, C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rb2exe-0.3.1/bin/traveling-ruby-2.2.2/osx/lib/libcrypto.dylib)" How do I fix?

**Comment by robinmenninga** [comment]
I don't know what OS you're on, but on Windows, run cmd as administrator and it'll install.
